disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 1
title = "Jaybird1291"

[params]
  displayName = "JA"
  isoCode = "ja"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/avatar.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Jaybird1291"
  image = "img/avatar.png"
  imageQuality = 100
  headline = "École2600の学生 <br> DFIR、iOSセキュリティ、およびRF分野に注力しています。"
  links = [
    { htb = "https://app.hackthebox.com/profile/1271052" },
    { cyberdefenders = "https://cyberdefenders.org/p/Jaybird1291#/overview" },
    { rootme = "https://www.root-me.org/Jaybird1291" },
    { thm = "https://tryhackme.com/p/Jaybird1291" },
    { discordo = "https://discordlookup.com/user/168778579281182721" },
    { mail = "mailto:jaybird1291.wcjg1@8alias.com" },
    { cherry-blossom = "https://jaybird1291.github.io/japanese/" },
  ]
